### ISSUE TITLE
客户端不支持Socket tcp4?

### ISSUE THREAD

**Issue by zouhuigang** [hprose/hprose-python#3]
golang用的是：
service := rpc.NewTCPServer("tcp4://0.0.0.0:3339")

python：

client=hprose.HttpClient('tcp4://0.0.0.0:3339')

运行报错：
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by andot** [comment]
嗯，这个版本还不支持 TCP 客户端。

**Comment by zouhuigang** [comment]
好的，谢谢。
